# Generated by Django 2.0.1 on 2018-01-19 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_home_team', models.PositiveIntegerField(blank=True, null=True)),
                ('hint_away_team', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Palpite',
                'verbose_name_plural': 'Palpites',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField(blank=True, null=True)),
                ('result_home_team', models.PositiveIntegerField(default=0)),
                ('result_away_team', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'MALE'), (2, 'FEMALE')], null=True)),
                ('sign_up_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('subscription', models.CharField(blank=True, max_length=10, null=True)),
                ('subscription_date', models.DateTimeField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=8, null=True)),
                ('street', models.CharField(blank=True, max_length=300, null=True)),
                ('number', models.CharField(blank=True, max_length=5, null=True)),
                ('complement', models.CharField(blank=True, max_length=300, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('pro', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='RealTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('realtournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RealTournament')),
            ],
            options={
                'verbose_name': 'Rodada',
                'verbose_name_plural': 'Rodadas',
            },
        ),
        migrations.CreateModel(
            name='SoccerTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Time de Futebol',
                'verbose_name_plural': 'Times de Futebol',
            },
        ),
        migrations.CreateModel(
            name='TeamCrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crest_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Grande'), (2, 'Pequeno'), (3, 'Médio')], null=True, verbose_name='Brasão')),
                ('stamp', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Grande'), (2, 'Pequeno'), (3, 'Médio')], null=True, verbose_name='Estampa')),
                ('adornment', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Grande'), (2, 'Pequeno'), (3, 'Médio')], null=True, verbose_name='Adorno')),
                ('collor1', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Verde'), (2, 'Vermelho'), (3, 'Azul'), (4, 'Amarelo'), (5, 'Preto')], null=True, verbose_name='Cor Brasão 1')),
                ('collor2', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Verde'), (2, 'Vermelho'), (3, 'Azul'), (4, 'Amarelo'), (5, 'Preto')], null=True, verbose_name='Cor Brasão 2')),
                ('collor3', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Verde'), (2, 'Vermelho'), (3, 'Azul'), (4, 'Amarelo'), (5, 'Preto')], null=True, verbose_name='Cor Brasão 3')),
            ],
            options={
                'verbose_name': 'Team Crest',
            },
        ),
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Time')),
                ('real_team', models.PositiveIntegerField(blank=True, choices=[(1, 'Corinthians'), (2, 'Vasco'), (3, 'Atletico_pr'), (4, 'Atletico_mg'), (5, 'Palmeiras')], null=True, verbose_name='Time do Coração')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
            options={
                'verbose_name': 'Team Data',
            },
        ),
        migrations.CreateModel(
            name='TeamShirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], null=True, verbose_name='Modelo da Camisa')),
                ('shirt_stamp', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], null=True, verbose_name='Estampa da Camisa')),
                ('collor1', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Verde'), (2, 'Vermelho'), (3, 'Azul'), (4, 'Amarelo'), (5, 'Preto')], null=True, verbose_name='Cor Brasão 1')),
                ('collor2', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Verde'), (2, 'Vermelho'), (3, 'Azul'), (4, 'Amarelo'), (5, 'Preto')], null=True, verbose_name='Cor Brasão 2')),
                ('collor3', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Verde'), (2, 'Vermelho'), (3, 'Azul'), (4, 'Amarelo'), (5, 'Preto')], null=True, verbose_name='Cor Brasão 3')),
                ('teamdata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.TeamData')),
            ],
            options={
                'verbose_name': 'Team Shirt',
            },
        ),
        migrations.CreateModel(
            name='TeamTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realtournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RealTournament')),
                ('soccerteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SoccerTeam')),
            ],
            options={
                'verbose_name': 'Torneio do Time',
                'verbose_name_plural': 'Torneios dos Times',
            },
        ),
        migrations.CreateModel(
            name='UserTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realtournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RealTournament')),
                ('teamdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TeamData')),
            ],
            options={
                'verbose_name': 'Torneio do Usuário',
                'verbose_name_plural': 'Torneios do Usuário',
            },
        ),
        migrations.AddField(
            model_name='teamcrest',
            name='teamdata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.TeamData'),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Round'),
        ),
        migrations.AddField(
            model_name='match',
            name='soccerteam_away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soccerteam_away', to='users.SoccerTeam'),
        ),
        migrations.AddField(
            model_name='match',
            name='soccerteam_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soccerteam_home', to='users.SoccerTeam'),
        ),
        migrations.AddField(
            model_name='hint',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Match'),
        ),
        migrations.AddField(
            model_name='hint',
            name='realtournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RealTournament'),
        ),
        migrations.AddField(
            model_name='hint',
            name='usertournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserTournament'),
        ),
    ]
