# Generated by Django 2.0.1 on 2018-01-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='real_team',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Corinthians'), (2, 'Vasco'), (3, 'Atletico_pr'), (4, 'Atletico_mg'), (5, 'Palmeiras'), (6, 'Botafogo')], null=True, verbose_name='Time do Coração'),
        ),
    ]
