# Generated by Django 2.0.1 on 2018-01-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='fullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='signUpDate',
            new_name='sign_up_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='subscriptionDate',
            new_name='subscription_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='zipCode',
            new_name='zip_code',
        ),
    ]
