# Generated by Django 2.0.1 on 2018-01-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180110_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='logradouro',
            new_name='street',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sign_up_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
