# Generated by Django 2.0.1 on 2018-01-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180119_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdata',
            name='real_team',
        ),
        migrations.AddField(
            model_name='teamdata',
            name='soccerteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SoccerTeam', verbose_name='Time do Coração'),
        ),
    ]
